version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: starmem/foodgram_backend
    volumes:
      - static:/backend_static
      - media:/app/media/
    env_file:
      - .env

  frontend:
    image: starmem/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: starmem/foodgram_gateway
    ports:
      - 9001:80
    volumes:
      - static:/staticfiles
      - media:/var/html/media/
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
